import json
import os
from dotenv import load_dotenv

load_dotenv()

BOT_TOKEN = os.getenv("BOT_TOKEN")
ROCKET_TOKEN = os.getenv("ROCKET_TOKEN")
CRYPTO_TOKEN = os.getenv("CRYPTO_TOKEN")

birds = [
    {"rarity": "Редкая", "name": "Сибирский мохноногий ястреб", "place": "Сибирь", "photo": "images/bird_rare.jpg",
     "points": "1000"},
    {"rarity": "Редкая", "name": "Большая синица", "place": "Сибирь", "photo": "images/bird_rare_2.jpg",
     "points": "1000"},
    {"rarity": "Редкая", "name": "Снегирь", "place": "Сибирь", "photo": "images/bird_rare_3.jpg", "points": "1000"},
    {"rarity": "Редкая", "name": "Ворон", "place": "Сибирь", "photo": "images/bird_rare_4.jpg", "points": "1000"},
    {"rarity": "Редкая", "name": "Хохлатая цапля", "place": "Хайфский округ", "photo": "images/bird_rare_5.jpg",
     "points": "1000"},
    {"rarity": "Редкая", "name": "Малый подорлик", "place": "Хайфский округ", "photo": "images/bird_rare_6.jpg",
     "points": "1000"},
    {"rarity": "Редкая", "name": "Зеленый дятел", "place": "Гейтер Лондон", "photo": "images/bird_rare_7.jpg",
     "points": "1000"},
    {"rarity": "Редкая", "name": "Королевский дрозд", "place": "Гейтер Лондон", "photo": "images/bird_rare_8.jpg",
     "points": "1000"},
    {"rarity": "Редкая", "name": "Южнополярный поморник", "place": "Антарктика", "photo": "images/bird_rare_9.jpg",
     "points": "1000"},
    {"rarity": "Редкая", "name": "Императорский пингвин", "place": "Антарктика", "photo": "images/bird_rare_10.jpg",
     "points": "1000"},
    {"rarity": "Сверхредкая", "name": "Евразийский древесный воробей", "place": "Сибирь",
     "photo": "images/bird_sverxrare.jpg", "points": "3000"},
    {"rarity": "Сверхредкая", "name": "Сосновый дубонос", "place": "Сибирь", "photo": "images/bird_sverxrare_2.jpg",
     "points": "3000"},
    {"rarity": "Сверхредкая", "name": "Сибирский клест", "place": "Сибирь", "photo": "images/bird_sverxrare_3.jpg",
     "points": "3000"},
    {"rarity": "Сверхредкая", "name": "Евразийский перепелятник", "place": "Сибирь",
     "photo": "images/bird_sverxrare_4.jpg", "points": "3000"},
    {"rarity": "Сверхредкая", "name": "Черный журавль", "place": "Хайфский округ",
     "photo": "images/bird_sverxrare_5.jpg", "points": "3000"},
    {"rarity": "Сверхредкая", "name": "Большой песчаник", "place": "Хайфский округ",
     "photo": "images/bird_sverxrare_6.jpg", "points": "3000"},
    {"rarity": "Сверхредкая", "name": "Черный дрозд", "place": "Гейтер Лондон", "photo": "images/bird_sverxrare_7.jpg",
     "points": "3000"},
    {"rarity": "Сверхредкая", "name": "Речная горлица", "place": "Гейтер Лондон",
     "photo": "images/bird_sverxrare_8.jpg", "points": "3000"},
    {"rarity": "Сверхредкая", "name": "Снежный буревестник", "place": "Антарктика",
     "photo": "images/bird_sverxrare_9.jpg", "points": "3000"},
    {"rarity": "Сверхредкая", "name": "Антарктическая бакланоподобная крачка", "place": "Антарктика",
     "photo": "images/bird_sverxrare_10.jpg", "points": "3000"},
    {"rarity": "Мифическая", "name": "Редполл", "place": "Сибирь", "photo": "images/bird_mific.jpg", "points": "5000"},
    {"rarity": "Мифическая", "name": "Сапсан", "place": "Сибирь", "photo": "images/bird_mific_2.jpg", "points": "5000"},
    {"rarity": "Мифическая", "name": "Чернозобый ныряльщик", "place": "Сибирь", "photo": "images/bird_mific_3.jpg",
     "points": "5000"},
    {"rarity": "Мифическая", "name": "Клест", "place": "Сибирь", "photo": "images/bird_mific_4.jpg", "points": "5000"},
    {"rarity": "Мифическая", "name": "Сип белоголовый", "place": "Хайфский округ", "photo": "images/bird_mific_5.jpg",
     "points": "5000"},
    {"rarity": "Мифическая", "name": "Дрофа", "place": "Хайфский округ", "photo": "images/bird_mific_6.jpg",
     "points": "5000"},
    {"rarity": "Мифическая", "name": "Воробей дубонос", "place": "Гейтер Лондон", "photo": "images/bird_mific_7.jpg",
     "points": "5000"},
    {"rarity": "Мифическая", "name": "Водяной пастушок", "place": "Гейтер Лондон", "photo": "images/bird_mific_8.jpg",
     "points": "5000"},
    {"rarity": "Мифическая", "name": "Голубоногий буревестник", "place": "Антарктика",
     "photo": "images/bird_mific_9.jpg", "points": "5000"},
    {"rarity": "Мифическая", "name": "Тонкоклювая буревестница", "place": "Антарктика",
     "photo": "images/bird_mific_10.jpg", "points": "5000"},
    {"rarity": "Легендарная", "name": "Сибирский глухарь", "place": "Сибирь", "photo": "images/bird_legendary.jpg",
     "points": "10000"},
    {"rarity": "Легендарная", "name": "Подвид белоголового орлана", "place": "Сибирь",
     "photo": "images/bird_legendary_2.jpg", "points": "10000"},
    {"rarity": "Легендарная", "name": "Бледный лунь", "place": "Сибирь", "photo": "images/bird_legendary_3.jpg",
     "points": "10000"},
    {"rarity": "Легендарная", "name": "Краснозобый ныряльщик", "place": "Сибирь",
     "photo": "images/bird_legendary_4.jpg", "points": "10000"},
    {"rarity": "Легендарная", "name": "Средиземноморская ржанка", "place": "Хайфский округ",
     "photo": "images/bird_legendary_5.jpg", "points": "10000"},
    {"rarity": "Легендарная", "name": "Змееяд", "place": "Хайфский округ", "photo": "images/bird_legendary_6.jpg",
     "points": "10000"},
    {"rarity": "Легендарная", "name": "Орлан белохвостый", "place": "Гейтер Лондон",
     "photo": "images/bird_legendary_7.jpg", "points": "10000"},
    {"rarity": "Легендарная", "name": "Желтый корольок", "place": "Гейтер Лондон",
     "photo": "images/bird_legendary_8.jpg", "points": "10000"},
    {"rarity": "Легендарная", "name": "Антарктическая камышовка", "place": "Антарктика",
     "photo": "images/bird_legendary_9.jpg", "points": "10000"},
    {"rarity": "Легендарная", "name": "Антарктический голубок", "place": "Антарктика",
     "photo": "images/bird_legendary_10.jpg", "points": "10000"},
    {"rarity": "Крутка", "name": "Птичка печенька", "place": "Конфетный лес", "photo": "images/bird_krutka.jpg"},
    {"rarity": "Крутка", "name": "Птичка Круассан", "place": "Конфетный лес", "photo": "images/bird_krutka_2.jpg"},
    {"rarity": "Крутка", "name": "Птичка тортик", "place": "Конфетный лес", "photo": "images/bird_krutka_3.jpg"},
    {"rarity": "Крутка", "name": "Птичка зефирка", "place": "Конфетный лес", "photo": "images/bird_krutka_4.jpg"}
]

birds_2 = [{'rarity': 'Редкая', 'name': 'Сибирский мохноногий ястреб', 'place': 'Сибирь', 'photo': 'AgACAgQAAyEGAASR4EFnAAIH1Gb4H2n3K0CuiAgPXp8wqiE9-9bDAAJIxTEbwqrAU53UkKl1Fm0jAQADAgADeQADNgQ', 'points': '1000'},
           {'rarity': 'Редкая', 'name': 'Большая синица', 'place': 'Сибирь', 'photo': 'AgACAgQAAyEGAASR4EFnAAIH42b4H4kAAZvVmGji41aWtQnoGhTmFAACSsUxG8KqwFP6WSZvHkPofwEAAwIAA3kAAzYE', 'points': '1000'},
           {'rarity': 'Редкая', 'name': 'Снегирь', 'place': 'Сибирь', 'photo': 'AgACAgQAAxkDAAIB3mb4KPwavJyM5_RkGHH_LEyWZsxOAAJTxTEbU_PAU3KsLmt_Cxw6AQADAgADeQADNgQ', 'points': '1000'},
           {'rarity': 'Редкая', 'name': 'Ворон', 'place': 'Сибирь', 'photo': 'AgACAgQAAyEGAASR4EFnAAIHt2b33utBU25pulHfcqqTgeMdVccsAALbwzEbwqq4U4J6zAxggXmZAQADAgADeQADNgQ', 'points': '1000'},
           {'rarity': 'Редкая', 'name': 'Хохлатая цапля', 'place': 'Хайфский округ', 'photo': 'AgACAgQAAx0Efr5rfQABCEhzZvfmQ07-Hs2uduFK8TkIfxlPc_MAAvbAMRsqd8FTGp6FXSLPkfwBAAMCAAN4AAM2BA', 'points': '1000'},
           {'rarity': 'Редкая', 'name': 'Малый подорлик', 'place': 'Хайфский округ', 'photo': 'AgACAgQAAyEGAASR4EFnAAIH3Wb4H3ox2MQoiVdOq9xI5S5HAjPgAAJJxTEbwqrAU5eKrCJzn5giAQADAgADeAADNgQ', 'points': '1000'},
           {'rarity': 'Редкая', 'name': 'Зеленый дятел', 'place': 'Гейтер Лондон', 'photo': 'AgACAgQAAxkDAAICHGb4SZZChXN-XvhalAlSovwX1LQNAAKvxTEbU_PAUyhfqICHdliJAQADAgADeQADNgQ', 'points': '1000'},
           {'rarity': 'Редкая', 'name': 'Королевский дрозд', 'place': 'Гейтер Лондон', 'photo': 'AgACAgQAAyEGAASR4EFnAAIHeWb3wFsELwoc-VwjW1ijCo94X60vAAKGwzEbwqq4U4EGx8QxDd-nAQADAgADeQADNgQ', 'points': '1000'},
           {'rarity': 'Редкая', 'name': 'Южнополярный поморник', 'place': 'Антарктика', 'photo': 'AgACAgQAAxkDAAIB3mb4KP6kYgABmpQJFZjC7uNDt4asOwACVMUxG1PzwFPr0wSyejVEuwEAAwIAA3gAAzYE', 'points': '1000'},
           {'rarity': 'Редкая', 'name': 'Императорский пингвин', 'place': 'Антарктика', 'photo': 'AgACAgQAAxkDAAICH2b4SaKduW-14qh9MmCxq0OnlyHWAAKwxTEbU_PAU6nM1mhdfpZ4AQADAgADeAADNgQ', 'points': '1000'},
           {'rarity': 'Редкая', 'name': 'Синешапочный элений', 'place': 'Борнео', 'photo': 'AgACAgQAAxkDAAID5Gb7_86SLczYHPulYTku1K6AAzcHAALRxjEbZUHgU70mnn53K2DsAQADAgADeQADNgQ', 'points': '1000'},
           {'rarity': 'Редкая', 'name': 'Малый малахитовый ракшун', 'place': 'Борнео', 'photo': 'AgACAgQAAxkDAAID6Gb7_9-6dP2TSsk36A9jf-5QhV3ZAALVxjEbZUHgU3HLuo-ZD29tAQADAgADeQADNgQ', 'points': '1000'},
           {'rarity': 'Сверхредкая', 'name': 'Евразийский древесный воробей', 'place': 'Сибирь', 'photo': 'AgACAgQAAxkDAAICIGb4SaYAAX3H_IbpfCaFpG_p4BKj8wACscUxG1PzwFPTvZ267e6uzQEAAwIAA3kAAzYE', 'points': '3000'},
           {'rarity': 'Сверхредкая', 'name': 'Сосновый дубонос', 'place': 'Сибирь', 'photo': 'AgACAgQAAxkDAAIB8mb4Rzimcx8NRj9TrXdyVuXdrwSfAAKqxTEbU_PAU1D62yQAActz0gEAAwIAA3kAAzYE', 'points': '3000'},
           {'rarity': 'Сверхредкая', 'name': 'Сибирский клест', 'place': 'Сибирь', 'photo': 'AgACAgQAAxkDAAICImb4SbBkmZ4ltq5gK21siLJWg5UJAAKyxTEbU_PAU4D3bC6Cns6_AQADAgADeQADNgQ', 'points': '3000'},
           {'rarity': 'Сверхредкая', 'name': 'Евразийский перепелятник', 'place': 'Сибирь', 'photo': 'AgACAgQAAxkDAAICFGb4SRXfzgu8AZoFlxWiyzMAAdNSiAACrcUxG1PzwFMvJeWSRAePzQEAAwIAA3kAAzYE', 'points': '3000'},
           {'rarity': 'Сверхредкая', 'name': 'Черный журавль', 'place': 'Хайфский округ', 'photo': 'AgACAgQAAxkDAAICJGb4SbiBUnY825gt4MWlbPcNu7hPAAKzxTEbU_PAU1Iam6HSGQoUAQADAgADeAADNgQ', 'points': '3000'},
           {'rarity': 'Сверхредкая', 'name': 'Большой песчаник', 'place': 'Хайфский округ', 'photo': 'AgACAgQAAxkDAAICEmb4SQ0hINBoTd0G4bLZkWzFRgllAAKsxTEbU_PAU6EQuTk_PxL6AQADAgADeAADNgQ', 'points': '3000'},
           {'rarity': 'Сверхредкая', 'name': 'Черный дрозд', 'place': 'Гейтер Лондон', 'photo': 'AgACAgQAAxkDAAICJmb4ScDBU-1TWTTvkeTUf9uVkKodAAK0xTEbU_PAU_O6ta5XW0eRAQADAgADeQADNgQ', 'points': '3000'},
           {'rarity': 'Сверхредкая', 'name': 'Речная горлица', 'place': 'Гейтер Лондон', 'photo': 'AgACAgQAAxkDAAIB8Wb4RzX8Y6z5xGvgv05RX9nS4-WdAAKpxTEbU_PAU8erqMWvncGvAQADAgADeQADNgQ', 'points': '3000'},
           {'rarity': 'Сверхредкая', 'name': 'Снежный буревестник', 'place': 'Антарктика', 'photo': 'AgACAgQAAx0Efr5rfQABCEiAZvf8jSnyT1RHT_1PX5EBqJBAIKYAAhjBMRsqd8FTUU0b3IjS-TUBAAMCAAN4AAM2BA', 'points': '3000'},
           {'rarity': 'Сверхредкая', 'name': 'Антарктическая бакланоподобная крачка', 'place': 'Антарктика', 'photo': 'AgACAgQAAyEGAASR4EFnAAIHcGb3v_pbhgaCKCAcjzfqwI9L4legAAKFwzEbwqq4U10jbB2OK01fAQADAgADeAADNgQ', 'points': '3000'},
           {'rarity': 'Сверхредкая', 'name': 'Большой носороговый калао', 'place': 'Борнео', 'photo': 'AgACAgQAAxkDAAID4mb7_8ZioJN397hQJFPjzETI5okiAALPxjEbZUHgU3RxBXOwgEw_AQADAgADeQADNgQ', 'points': '3000'},
           {'rarity': 'Сверхредкая', 'name': 'Черношейная корольковая мухоловка', 'place': 'Борнео', 'photo': 'AgACAgQAAxkDAAID5Wb7_9Obnih8n1CtM0gOsIfYgPrbAALSxjEbZUHgU4zhWSiEKnFhAQADAgADeQADNgQ', 'points': '3000'},
           {'rarity': 'Мифическая', 'name': 'Редполл', 'place': 'Сибирь', 'photo': 'AgACAgQAAxkDAAICKmb4Sc9_mkkXu6BNjjA1nFLVEqHuAAK2xTEbU_PAUyQx8cpDhiOEAQADAgADeQADNgQ', 'points': '5000'},
           {'rarity': 'Мифическая', 'name': 'Сапсан', 'place': 'Сибирь', 'photo': 'AgACAgQAAyEGAASR4EFnAAIHY2b3mw35fiOzB20Qca6OGf8X1OfuAAJdwzEbwqq4U_1xqwABKzP1tAEAAwIAA3kAAzYE', 'points': '5000'},
           {'rarity': 'Мифическая', 'name': 'Чернозобый ныряльщик', 'place': 'Сибирь', 'photo': 'AgACAgQAAxkDAAICLGb4Sdejcoac5f6RokCtEf7qL4ubAAK3xTEbU_PAU3ZSmVW1V6AgAQADAgADeQADNgQ', 'points': '5000'},
           {'rarity': 'Мифическая', 'name': 'Клест', 'place': 'Сибирь', 'photo': 'AgACAgQAAxkDAAICLWb4SdvTMxOOrAABJZ_NEE71EQ3u6QACuMUxG1PzwFPw3q4N_YPaRgEAAwIAA3kAAzYE', 'points': '5000'},
           {'rarity': 'Мифическая', 'name': 'Сип белоголовый', 'place': 'Хайфский округ', 'photo': 'AgACAgQAAxkDAAIB7Wb4RzFknUEAAemq4StskCbHRtz-RAACp8UxG1PzwFOUqQwnBu5nggEAAwIAA3gAAzYE', 'points': '5000'},
           {'rarity': 'Мифическая', 'name': 'Дрофа', 'place': 'Хайфский округ', 'photo': 'AgACAgQAAxkDAAIBtWb34LlE9TEnZxX7SVBCGyVcIqRHAAJXwzEbfDHAU_w9zPRIXPMnAQADAgADeAADNgQ', 'points': '5000'},
           {'rarity': 'Мифическая', 'name': 'Воробей дубонос', 'place': 'Гейтер Лондон', 'photo': 'AgACAgQAAxkDAAIB9mb4R0BjeETU-Xhsj_wegaYZ893AAAKrxTEbU_PAU-taYi8OQTf5AQADAgADeQADNgQ', 'points': '5000'},
           {'rarity': 'Мифическая', 'name': 'Водяной пастушок', 'place': 'Гейтер Лондон', 'photo': 'AgACAgQAAxkDAAICMWb4SerGOiztDXjTnJtHDJmBCpLvAAK5xTEbU_PAU_RG7QZ4JJwGAQADAgADeQADNgQ', 'points': '5000'},
           {'rarity': 'Мифическая', 'name': 'Голубоногий буревестник', 'place': 'Антарктика', 'photo': 'AgACAgQAAxkDAAICMmb4Se7Kyj3T8aSvKrX6BvTBFdfaAAK6xTEbU_PAU9ABcpgovRcWAQADAgADeAADNgQ', 'points': '5000'},
           {'rarity': 'Мифическая', 'name': 'Тонкоклювая буревестница', 'place': 'Антарктика', 'photo': 'AgACAgQAAxkDAAICM2b4SfIZ2T022PyRm8nfiwMZ82t2AAK7xTEbU_PAUyLoVeVLQBnfAQADAgADeAADNgQ', 'points': '5000'},
           {'rarity': 'Мифическая', 'name': 'Серебристая листовая курица', 'place': 'Борнео', 'photo': 'AgACAgQAAxkDAAID5mb7_9cG-jpd7f5GY2UMyuXAU5BGAALTxjEbZUHgU4ZT0m92x6IdAQADAgADeQADNgQ', 'points': '5000'},
           {'rarity': 'Мифическая', 'name': 'Борнейская зеленая голубка', 'place': 'Борнео', 'photo': 'AgACAgQAAxkDAAID52b7_9uBuOC7ICmrKrAatPg8FFVmAALUxjEbZUHgU-CpScrCJxT0AQADAgADeQADNgQ', 'points': '5000'},
           {'rarity': 'Легендарная', 'name': 'Сибирский глухарь', 'place': 'Сибирь', 'photo': 'AgACAgQAAxkDAAICNGb4SfYmtneM6yVIdx41MPD7XXLsAAK8xTEbU_PAUyGlanFswGs5AQADAgADeQADNgQ', 'points': '10000'},
           {'rarity': 'Легендарная', 'name': 'Подвид белоголового орлана', 'place': 'Сибирь', 'photo': 'AgACAgQAAxkDAAICNWb4SfogSya9BHVZotD__9wv3HxfAAK9xTEbU_PAU6ESzhhZXzOjAQADAgADeQADNgQ', 'points': '10000'},
           {'rarity': 'Легендарная', 'name': 'Бледный лунь', 'place': 'Сибирь', 'photo': 'AgACAgQAAxkDAAIBwWb3449HoJVn52Q8Z61jRiuURSCZAAJiwzEbfDHAU7TQks1h3dFvAQADAgADeQADNgQ', 'points': '10000'},
           {'rarity': 'Легендарная', 'name': 'Краснозобый ныряльщик', 'place': 'Сибирь', 'photo': 'AgACAgQAAxkDAAICN2b4SgIQjrfyCaPSu0plzvRG6O_QAAK-xTEbU_PAU8Lp40O1E0FSAQADAgADeQADNgQ', 'points': '10000'},
           {'rarity': 'Легендарная', 'name': 'Средиземноморская ржанка', 'place': 'Хайфский округ', 'photo': 'AgACAgQAAxkDAAICOGb4SgZgSCKYRwGYPAVzb1JfVIPBAAK_xTEbU_PAUyTpS8BpsyjrAQADAgADeAADNgQ', 'points': '10000'},
           {'rarity': 'Легендарная', 'name': 'Змееяд', 'place': 'Хайфский округ', 'photo': 'AgACAgQAAyEGAASR4EFnAAIHa2b3m0ooZAcYXeU8_KiPbE68ghNWAAJewzEbwqq4U7xiMDJ8MzRfAQADAgADeAADNgQ', 'points': '10000'},
           {'rarity': 'Легендарная', 'name': 'Орлан белохвостый', 'place': 'Гейтер Лондон', 'photo': 'AgACAgQAAxkDAAIBs2b34LCFwZBbywJKy0oUT1ED9glPAAJWwzEbfDHAU_bB1ghPQWIkAQADAgADeQADNgQ', 'points': '10000'},
           {'rarity': 'Легендарная', 'name': 'Желтый корольок', 'place': 'Гейтер Лондон', 'photo': 'AgACAgQAAxkDAAICO2b4ShH2RiI_t3i04KMjGC2Jmba8AALAxTEbU_PAU7y8UhgSSaeZAQADAgADeQADNgQ', 'points': '10000'},
           {'rarity': 'Легендарная', 'name': 'Антарктическая камышовка', 'place': 'Антарктика', 'photo': 'AgACAgQAAxkDAAICPGb4ShWkRapxmsRYIZk3v-lxZ15RAALBxTEbU_PAU5eu339Hn7PbAQADAgADeAADNgQ', 'points': '10000'},
           {'rarity': 'Легендарная', 'name': 'Антарктический голубок', 'place': 'Антарктика', 'photo': 'AgACAgQAAxkDAAICPWb4ShnFtI7b7fNqx-2JFBPTimlaAALCxTEbU_PAU6fqGgZo_2MAAQEAAwIAA3gAAzYE', 'points': '10000'},
           {'rarity': 'Легендарная', 'name': 'Большеклювый дятел', 'place': 'Борнео', 'photo': 'AgACAgQAAxkDAAID6Wb7_-NiDyOFv9cx7xD_sFpYS5CxAALWxjEbZUHgU7hoomx5BvMMAQADAgADeQADNgQ', 'points': '10000'},
           {'rarity': 'Легендарная', 'name': 'Красногорлый борнейский павлин-фазан', 'place': 'Борнео', 'photo': 'AgACAgQAAxkDAAID42b7_8oJWaJTFuwHi_kiKLqeLe7NAALQxjEbZUHgU4VtGXwcto7cAQADAgADeQADNgQ', 'points': '10000'},
           {'rarity': 'Крутка', 'name': 'Птичка печенька', 'place': 'Конфетный лес', 'photo': 'AgACAgQAAxkDAAIBvGb34ZkEqQWDlmw40NgHGU1Ad1jSAAJawzEbfDHAU21SU7lk_NUeAQADAgADeAADNgQ'},
           {'rarity': 'Крутка', 'name': 'Птичка Круассан', 'place': 'Конфетный лес', 'photo': 'AgACAgQAAxkDAAIB8Gb4RzTaFZZSlrwwU-3mJWFoVywxAAKoxTEbU_PAU4VMGyvH5iK-AQADAgADeAADNgQ'},
           {'rarity': 'Крутка', 'name': 'Птичка тортик', 'place': 'Конфетный лес', 'photo': 'AgACAgQAAx0Efr5rfQABCEiXZvgtIIczqi7JXZMXFYatM4-2Y9oAAtvJMRvss8BTPn86R8Qf47oBAAMCAAN4AAM2BA'},
           {'rarity': 'Крутка', 'name': 'Птичка зефирка', 'place': 'Конфетный лес', 'photo': 'AgACAgQAAxkDAAICQWb4SihtKkUTVTOPgZY0Z0K_y24fAALDxTEbU_PAU7hVxQlVfd2RAQADAgADeAADNgQ'}
]
